// AUTOGENERATED Components module
pub mod card;
pub mod select;
pub mod input;
pub mod tabs;
pub mod separator;
pub mod button;
pub mod dialog;
pub mod label;
pub mod textarea;
pub mod badge;
pub mod sheet;
pub mod sidebar;
pub mod tooltip;
pub mod skeleton;
